module.exports = {
  DEBUG: 'DEBUG',

  // ACTIVE_CLUSTER
  GET_ACTIVE_CLUSTER: 'GET_ACTIVE_CLUSTER',
  HIDE_ACTIVE_CLUSTER: 'HIDE_ACTIVE_CLUSTER',
  SET_ACTIVE_CLUSTER: 'SET_ACTIVE_CLUSTER',
  SHOW_ACTIVE_CLUSTER: 'SHOW_ACTIVE_CLUSTER',
  UPDATE_ACTIVE_CLUSTER: 'UPDATE_ACTIVE_CLUSTER',

  // LOGS
  GET_LOGS: 'GET_LOGS',
  HIDE_LOGS: 'HIDE_LOGS',
  SET_LOGS: 'SET_LOGS',
  SHOW_LOGS: 'SHOW_LOGS',

  // PODS
  GET_PODS: 'GET_PODS',
  HIDE_PODS: 'SET_PODS',
  SET_PODS: 'SET_PODS',
  SHOW_PODS: 'SET_PODS',
  UPDATE_PODS: 'UPDATE_PODS',
};
